# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

def required_pods

  # Reactive
  pod 'RxSwift', '5.1.3'
  pod 'RxCocoa'
  pod 'RxAlamofire'
  pod 'RxDataSources'
  pod 'RxRestClient'
  # pod 'RxSwiftExt', :git => 'https://github.com/RxSwiftCommunity/RxSwiftExt.git', :commit => '3b03aa7'


  # Network
  pod 'Alamofire'
  pod 'Alamofire-Synchronous'

  # DB
  pod "Realm"
  pod "RealmSwift"
  # pod "RxRealm", :git => 'https://github.com/RxSwiftCommunity/RxRealm.git', :commit => '5431fe1'

  # Util
  pod 'R.swift'
  pod 'Swinject'
  pod 'SwiftyUserDefaults'
  pod 'SDWebImage'


  # UI
  pod 'SwiftMessages'

end

target 'skyeng-External' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for skyeng-External
  required_pods

  target 'skyeng-ExternalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'skyeng-ExternalUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          end
      end
  end
  
    
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Debug'
        config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-Onone']
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      end
    end
  end
end
